easy_admin:
    entities:
        # List the entity class name you want to manage
        BlogPost:
            class: App\Entity\BlogPost
            form:
                fields:
                  - { property: 'title', help: 'Title' }
                  - { property: 'content', help: 'Content' }
        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'username', help: 'Username' }
                    - { property: 'username', help: 'Email' }
