easy_admin:
    entities:
        # List the entity class name you want to manage
        BlogPost:
            class: App\Entity\BlogPost
            form:
                fields:
                    - title
                    - { property: 'title', label: 'Title' }
                    - content
                    - { property: 'content', help: 'Content' }
                    - media
                    - { property: 'media', help: 'Media', type: 'Donjohn\MediaBundle\Form\Type\MediaType', type_options: { media_class: 'App\Entity\Media', multiple: false, provider: 'image' } }
        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'username', help: 'Username' }
                    - { property: 'username', help: 'Email' }
