easy_admin:
    entities:
        # List the entity class name you want to manage
        BlogPost:
            class: App\Entity\BlogPost
            form:
                fields:
                  - { property: 'title', help: 'Title' }
                  - { property: 'content', help: 'Content' }
                  - { property: 'state', type: 'App\Form\Type\JsonType' }
